# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Dell.CommandEndpointConfigure.Intune
PackageVersion: 2.0.5.175
PackageLocale: en-US
Publisher: Dell Inc.
PublisherUrl: https://www.dell.com/support/kbdoc/en-us/000214308/dell-command-endpoint-configure-for-microsoft-intune
PublisherSupportUrl: https://www.dell.com/support/home/en-us
Author: Dell Inc.
PackageName: Dell Command | Endpoint Configure for Microsoft Intune
PackageUrl: https://www.dell.com/support/kbdoc/en-us/000214308/dell-command-endpoint-configure-for-microsoft-intune
License: Proprietary
LicenseUrl: https://www.dell.com/learn/us/en/uscorp1/terms-of-sale-consumer-license-agreements
Copyright: Copyright (c) Dell Inc.
CopyrightUrl: https://www.dell.com/en-us/legal/lp/site-terms-of-use-copyright
ShortDescription: Dell Command | Endpoint Configure for Microsoft Intune (DCECMI) provides a way to configure and secure the BIOS configurations on Dell computers using Microsoft Intune.
Description: Dell Command | Endpoint Configure for Microsoft Intune allows a secure package-based approach to push custom BIOS settings. These BIOS settings are configured using the Dell Command | Configure application and then applied to the BIOS using DCECMI at the endpoint.
Tags:
- dell
- bios
- intune
- mdm
- firmware
- endpoint-management
- enterprise
ReleaseNotesUrl: https://www.dell.com/support/kbdoc/en-us/000214308/dell-command-endpoint-configure-for-microsoft-intune
ManifestType: defaultLocale
ManifestVersion: 1.12.0
