ManifestVersion: 1.12.0ManifestVersion: 1.12.0ManifestVersion: 1.12.0ManifestVers# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Dell.CommandEndpointConfigure.Intune
PackageVersion: 2.0.5.175
InstallerType: exe
Scope: machine
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: install
ReleaseDate: 2026-09-15
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
Installers:
  - Architecture: x64
    InstallerUrl: https://dl.dell.com/FOLDER14990651M/1/Dell-Command-Endpoint-Configure-for-Microsoft-Intune_CGKCH_WIN64_2.0.5.175_A00.EXE
    InstallerSha256: 596C690349D81AA324D76F76127CFFA8E5CEA356AACDA74B045C0D619CE34855

  - Architecture: arm64
    InstallerUrl: https://dl.dell.com/FOLDER14990651M/1/Dell-Command-Endpoint-Configure-for-Microsoft-Intune_CGKCH_WIN64_2.0.5.175_A00.EXE
    InstallerSha256: 596C690349D81AA324D76F76127CFFA8E5CEA356AACDA74B045C0D619CE34855

ManifestType: installer
ManifestVersion: 1.12.0
